name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

concurrency:
  group: devops-pr-hygiene-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@8ff19efd329b76bce5ff5b98074b9aec74b239da # v1.8.1
    with:
      require-scope: false

  actionlint:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@8ff19efd329b76bce5ff5b98074b9aec74b239da # v1.8.1
    with:
      working-directory: "."
